# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20180417_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_text', models.CharField(max_length=20, verbose_name=b'Type of order orderd')),
                ('time', models.DateTimeField(verbose_name=b'Time')),
                ('instrument', models.CharField(max_length=10)),
                ('units', models.IntegerField(default=100000)),
                ('price', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='fill',
            name='create',
        ),
        migrations.AlterField(
            model_name='fill',
            name='fill_text',
            field=models.CharField(max_length=200, verbose_name=b'Type of order filled'),
        ),
        migrations.DeleteModel(
            name='Create',
        ),
        migrations.AddField(
            model_name='fill',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='currencies.Order'),
            preserve_default=False,
        ),
    ]
