# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_auto_20180417_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='fill',
            name='take_profit',
        ),
        migrations.AlterField(
            model_name='fill',
            name='fill_text',
            field=models.CharField(max_length=200, verbose_name=b'Order Type'),
        ),
    ]
