# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_auto_20180417_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='order',
        ),
        migrations.RemoveField(
            model_name='fill',
            name='units',
        ),
        migrations.RemoveField(
            model_name='order',
            name='instrument',
        ),
        migrations.AlterField(
            model_name='fill',
            name='fill_text',
            field=models.CharField(max_length=200, verbose_name=b'Stop Loss, Take Profit'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_text',
            field=models.CharField(max_length=10, verbose_name=b'Instrument'),
        ),
    ]
