# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0007_auto_20180417_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
