# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_text', models.CharField(max_length=20, verbose_name=b'Type of order created')),
                ('time', models.DateTimeField(verbose_name=b'Time')),
                ('instrument', models.CharField(max_length=10)),
                ('units', models.IntegerField(default=100000)),
                ('price', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_text', models.CharField(max_length=200, verbose_name=b'Typeof order filled')),
                ('time', models.DateTimeField(verbose_name=b'Time')),
                ('instrument', models.CharField(max_length=10)),
                ('units', models.IntegerField(default=100000)),
                ('price', models.DecimalField(decimal_places=5, max_digits=6)),
                ('create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Create')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
