# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_auto_20180417_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='stop_loss',
            field=models.CharField(default=0, max_length=200, verbose_name=b'Stop Loss'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fill',
            name='take_profit',
            field=models.CharField(default=0, max_length=200, verbose_name=b'Take Profit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fill',
            name='fill_text',
            field=models.CharField(max_length=200, verbose_name=b'Market Order'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='units',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
